### ISSUE TITLE
Ordering of Scenarios

### ISSUE THREAD

**Issue by kameshsampath** [projectodd/openwhisk-katacoda#23]
Lets Order the Scenarios based on increasing level of complexity:

1.  Simple Javascript Greeting Function
2. (Possibly Packages)
3. Web Accessible Actions on OCF
4. Chained Actions on OCF
5. Rules and Triggers on OCF

**Comment by jimcurtis** [comment]
It is much easier to change the ordering on learn.openshift.com as it is just a matter of changing the manifest rather than changing a bunch of directory names.  We will try to get more feedback on the ordering at Summit and make changes based on that.  Once, we have the ordering right on learn.openshift.com, we can go back and update it to match here.

**Comment by kameshsampath** [comment]
You could have waited to be tracked before closing :)

**Comment by kameshsampath** [comment]
Still I bet having rules at where it is now will definitely confuse students. Thats my personal experience doing serverless evangelism :). But I will leave it to you guys.
